### ISSUE TITLE
Invalid Version: 2.8 error

### ISSUE THREAD

**Issue by hueniverse** [creativelive/mdchangelog#24]
eran@monterey:~/code/hapi$ make changelog
[hapijs/hapi] fetching 1245/1245 issues [====================] 100% 0.0s
[moment/moment] fetching 662/662 issues [====================] 100% 0.0s
[hapijs/mimos] fetching 7/7 issues [====================] 100% 0.0s
[hapijs/joi] fetching 286/286 issues [====================] 100% 0.0s
[hapijs/call] fetching 7/7 issues [====================] 100% 0.0s
[hapijs/hoek] fetching 87/87 issues [====================] 100% 0.0s
[hapijs/catbox] fetching 76/76 issues [====================] 100% 0.0s
[hapijs/qs] fetching 43/43 issues [====================] 100% 0.0s
[hapijs/boom] fetching 27/27 issues [====================] 100% 0.0s

/usr/local/lib/node_modules/mdchangelog/node_modules/semver/semver.js:273
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: 2.8
    at new SemVer (/usr/local/lib/node_modules/mdchangelog/node_modules/semver/semver.js:273:11)
    at compare (/usr/local/lib/node_modules/mdchangelog/node_modules/semver/semver.js:493:10)
    at Function.gt (/usr/local/lib/node_modules/mdchangelog/node_modules/semver/semver.js:522:10)
    at /usr/local/lib/node_modules/mdchangelog/lib/formatter.js:28:20
    at Array.forEach (native)
    at findDependents (/usr/local/lib/node_modules/mdchangelog/lib/formatter.js:27:43)
    at formatIssue (/usr/local/lib/node_modules/mdchangelog/lib/formatter.js:42:3)
    at /usr/local/lib/node_modules/mdchangelog/lib/formatter.js:61:14
    at Array.forEach (native)
    at /usr/local/lib/node_modules/mdchangelog/lib/formatter.js:60:27
    at Array.forEach (native)
make: *** [changelog] Error 8

**Comment by diffsky** [comment]
semver, how does it work?
